# Generated by Django 5.2.17 on 2026-09-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF/CNPJ"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="endereço"
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=80)),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Financiamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: unidade, lote, empreendimento.",
                        max_length=150,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="nº documento"
                    ),
                ),
                (
                    "total_parcelas",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vazio para títulos avulsos (entradas, intermediárias).",
                        null=True,
                    ),
                ),
                ("data_entrada", models.DateField(blank=True, null=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financiamentos",
                        to="financeiro.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["cliente__nome", "data_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="nº"
                    ),
                ),
                (
                    "nosso_numero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="nosso número",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vencimento", models.DateField()),
                (
                    "data_limite",
                    models.DateField(
                        editable=False,
                        help_text="Vencimento + 1 mês. Depois desta data a parcela não paga fica vencida.",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de pagamento"
                    ),
                ),
                (
                    "requer_verificacao",
                    models.BooleanField(
                        default=False,
                        help_text="Baixada pelo banco antes de vencer; precisa de análise.",
                        verbose_name="baixado - verificar",
                    ),
                ),
                (
                    "situacao_banco",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="situação no banco"
                    ),
                ),
                (
                    "ultimo_comando_banco",
                    models.DateField(
                        blank=True, null=True, verbose_name="último comando no banco"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "financiamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="financeiro.financiamento",
                    ),
                ),
            ],
            options={
                "ordering": ["financiamento", "vencimento", "numero"],
                "indexes": [
                    models.Index(
                        fields=["data_limite"], name="financeiro__data_li_bf7c2a_idx"
                    ),
                    models.Index(
                        fields=["vencimento"], name="financeiro__vencime_278ea7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("numero__isnull", False)),
                        fields=("financiamento", "numero"),
                        name="parcela_numero_unico_por_financiamento",
                    )
                ],
            },
        ),
    ]
