# Generated by Django 5.2.17 on 2026-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TituloExcluido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nosso_numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="nosso número"
                    ),
                ),
                ("cliente", models.CharField(blank=True, max_length=150)),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descrição"
                    ),
                ),
                (
                    "excluido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="excluído em"),
                ),
            ],
            options={
                "verbose_name": "título excluído",
                "verbose_name_plural": "títulos excluídos",
                "ordering": ["-excluido_em"],
            },
        ),
    ]
