# Generated by Django 5.2.17 on 2026-09-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_grupos_de_acesso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="usuário"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Entrou"),
                            ("LOGOUT", "Saiu"),
                            ("LOGIN_FALHOU", "Login falhou"),
                            ("IMPORTACAO", "Importou extrato"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
