# Generated by Django 5.2.17 on 2026-09-30 14:11

import django.db.models.deletion
import financeiro.validadores
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_atividade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[financeiro.validadores.validar_cep],
                verbose_name="CEP",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True,
                max_length=18,
                validators=[financeiro.validadores.validar_cpf_cnpj],
                verbose_name="CPF/CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(
                blank=True,
                help_text="Rua, número e complemento.",
                max_length=200,
                verbose_name="endereço",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="uf",
            field=models.CharField(
                blank=True,
                max_length=2,
                validators=[financeiro.validadores.validar_uf],
                verbose_name="UF",
            ),
        ),
        migrations.CreateModel(
            name="PendenciaCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nosso_numero",
                    models.CharField(max_length=20, verbose_name="nosso número"),
                ),
                ("cliente", models.CharField(max_length=150)),
                (
                    "descricao_parcela",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="parcela"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Pedido de baixa"),
                            ("ALTERAR_VENCIMENTO", "Alterar vencimento"),
                            ("ALTERAR_VALOR", "Alterar valor"),
                            ("ALTERAR_PAGADOR", "Alterar dados do pagador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("antes", models.JSONField(blank=True, default=dict)),
                ("depois", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENVIADA", "Enviada à Caixa"),
                            ("CONFIRMADA", "Confirmada pelo extrato"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "enviado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enviada em"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="enviada por",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pendencias_caixa",
                        to="financeiro.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "alteração pendente para a Caixa",
                "verbose_name_plural": "alterações pendentes para a Caixa",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["status", "tipo"], name="financeiro__status_ae22fc_idx"
                    )
                ],
            },
        ),
    ]
