# Generated by Django 5.2.17 on 2026-10-01 17:05

import django.core.validators
import django.db.models.deletion
import financeiro.validadores
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_permissoes_pendencias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvenioCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "Informe 4 dígitos."
                            )
                        ],
                        verbose_name="agência",
                    ),
                ),
                (
                    "dv_agencia",
                    models.CharField(
                        blank=True,
                        help_text="Informado pela Caixa (vai no arquivo de remessa).",
                        max_length=1,
                        verbose_name="dígito da agência",
                    ),
                ),
                (
                    "codigo_beneficiario",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{7}$",
                                "Informe os 7 dígitos do código (sem o dígito verificador).",
                            )
                        ],
                        verbose_name="código do beneficiário",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        validators=[financeiro.validadores.validar_cpf_cnpj],
                        verbose_name="CPF/CNPJ do beneficiário",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True,
                        help_text="Como está no convênio da Caixa.",
                        max_length=30,
                        verbose_name="nome da empresa",
                    ),
                ),
                (
                    "ambiente_teste",
                    models.BooleanField(
                        default=True,
                        help_text="Enquanto a Caixa não liberar a produção, as remessas saem como REMESSA-TESTE e não alteram nada no banco (as pendências continuam pendentes).",
                        verbose_name="em teste na Caixa",
                    ),
                ),
                (
                    "especie_titulo",
                    models.CharField(
                        default="02",
                        help_text="Código da espécie (02 = DM, 99 = outros).",
                        max_length=2,
                        verbose_name="espécie do título",
                    ),
                ),
                (
                    "juros_codigo",
                    models.CharField(
                        choices=[
                            ("3", "Isento"),
                            ("1", "Valor por dia"),
                            ("2", "Taxa mensal"),
                        ],
                        default="3",
                        max_length=1,
                        verbose_name="juros de mora",
                    ),
                ),
                (
                    "juros_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Valor em R$ por dia ou % ao mês, conforme a opção acima.",
                        max_digits=13,
                        verbose_name="valor/taxa dos juros",
                    ),
                ),
                (
                    "protesto_codigo",
                    models.CharField(
                        choices=[("3", "Não protestar"), ("1", "Protestar")],
                        default="3",
                        max_length=1,
                        verbose_name="protesto",
                    ),
                ),
                (
                    "protesto_dias",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="dias para protesto"
                    ),
                ),
                (
                    "devolucao_dias",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Dias corridos depois do vencimento.",
                        verbose_name="dias para baixa/devolução",
                    ),
                ),
            ],
            options={
                "verbose_name": "convênio Caixa",
                "verbose_name_plural": "convênio Caixa",
            },
        ),
        migrations.AddField(
            model_name="pendenciacaixa",
            name="titulo",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name="RemessaCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nsa",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="nº sequencial (NSA)"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="gerada em"),
                ),
                (
                    "teste",
                    models.BooleanField(default=False, verbose_name="remessa de teste"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=0, verbose_name="títulos"),
                ),
                ("conteudo", models.TextField(editable=False, verbose_name="conteúdo")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gerada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "remessa para a Caixa",
                "verbose_name_plural": "remessas para a Caixa",
                "ordering": ["-nsa"],
            },
        ),
        migrations.AddField(
            model_name="pendenciacaixa",
            name="remessa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendencias",
                to="financeiro.remessacaixa",
            ),
        ),
    ]
