# Generated by Django 5.2.17 on 2026-10-01 18:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_convenio_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conveniocaixa",
            name="multa_codigo",
            field=models.CharField(
                choices=[("0", "Sem multa"), ("1", "Valor fixo"), ("2", "Percentual")],
                default="0",
                help_text="Cobrada a partir do dia seguinte ao vencimento.",
                max_length=1,
                verbose_name="multa",
            ),
        ),
        migrations.AddField(
            model_name="conveniocaixa",
            name="multa_valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Valor em R$ ou % sobre o valor do boleto, conforme a opção acima.",
                max_digits=13,
                verbose_name="valor/percentual da multa",
            ),
        ),
    ]
